sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ARAVINDH8770/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ARAVINDH8770/docker-react npm run test
